version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - '80:80'
    networks:
      - apinet
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - apinet


networks:
  apinet:
