version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
